package pl.strava.analizator.domain.model;

import java.math.BigDecimal;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;

/**
 * Training recommendation generated by a TrainingAdvisor.
 */
@Getter
@Builder
@AllArgsConstructor
public class TrainingRecommendation {

    private String advisorName;
    private String type;          // e.g. "endurance", "intervals", "recovery", "rest"
    private String message;       // human-readable recommendation
    private String reasoning;     // why this recommendation
    private BigDecimal targetTss;
    private Integer targetDurationMin;
    private Severity severity;

    public enum Severity {
        INFO, WARNING, ALERT
    }
}
