package pl.strava.analizator.domain.ai;

public enum PredictionType {

    FTP_PREDICTION,
    FATIGUE_PREDICTION,
    TRAINING_TYPE_RECOMMENDATION,
    PERFORMANCE_TREND,
    OVERTRAINING_RISK,
    RACE_READINESS,
    TRAINING_COACH_SUMMARY,
    RACE_PACING_STRATEGY,
    NUTRITION_PLAN,
    RECOVERY_PLAN,
    INJURY_RISK,
    PEAK_TIMING
}
