package pl.strava.analizator.application.ai;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import pl.strava.analizator.domain.ai.AiTool;
import pl.strava.analizator.domain.ai.LlmChatResponse;
import pl.strava.analizator.domain.ai.LlmMessage;
import pl.strava.analizator.domain.ai.LlmPort;
import pl.strava.analizator.domain.ai.ToolCall;
import pl.strava.analizator.domain.ai.ToolResult;

/**
 * Agentic tool-calling loop.
 * <p>
 * Sends the prompt to the LLM with available tools attached. If the model
 * requests tool calls, this service executes them and feeds results back until
 * the model produces a final text response or the iteration limit is reached.
 */
@Service
public class ToolCallingLoop {

    private static final Logger log = LoggerFactory.getLogger(ToolCallingLoop.class);
    private static final int MAX_ITERATIONS = 6;

    private final McpToolService toolService;
    private final LlmProviderRegistry providerRegistry;

    public ToolCallingLoop(McpToolService toolService, LlmProviderRegistry providerRegistry) {
        this.toolService = toolService;
        this.providerRegistry = providerRegistry;
    }

    /**
     * Runs the agentic loop with tool access.
     *
     * @param systemPrompt       coaching system instructions
     * @param userPrompt         activity + historical context
     * @param contextActivityId  ID of the activity being analysed (passed to tools)
     * @param providerName       LLM provider name (e.g. "ollama")
     * @param modelId            model identifier
     * @return final text generated by the LLM
     */
    public String run(String systemPrompt, String userPrompt,
                      UUID contextActivityId, String providerName, String modelId) {

        LlmPort provider = providerRegistry.getProvider(providerName);
        List<AiTool> tools = toolService.getToolDefinitions();

        List<LlmMessage> messages = new ArrayList<>();
        messages.add(LlmMessage.system(systemPrompt));
        messages.add(LlmMessage.user(userPrompt));

        for (int iteration = 0; iteration < MAX_ITERATIONS; iteration++) {
            LlmChatResponse response = provider.chatWithTools(messages, tools, modelId);

            if (response instanceof LlmChatResponse.Text text) {
                log.debug("Tool loop finished after {} iteration(s)", iteration + 1);
                return text.content();
            }

            if (response instanceof LlmChatResponse.ToolCalls tc) {
                log.debug("Iteration {}: model requested {} tool call(s): {}",
                        iteration + 1, tc.calls().size(),
                        tc.calls().stream().map(ToolCall::name).toList());

                // Append assistant message with tool calls
                messages.add(LlmMessage.assistantWithToolCalls(tc.calls()));

                // Execute each tool and append results
                for (ToolCall call : tc.calls()) {
                    ToolResult result = toolService.execute(call, contextActivityId);
                    log.debug("Tool [{}] returned {} chars", call.name(), result.content().length());
                    messages.add(LlmMessage.toolResult(result));
                }
            }
        }

        log.warn("Tool calling loop hit max iterations ({}), falling back to plain chat", MAX_ITERATIONS);
        return provider.chat(systemPrompt, userPrompt, modelId);
    }
}
