spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  flyway:
    clean-disabled: false

logging:
  level:
    pl.strava.analizator: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
