-- AI Activity Notes: per-activity coach analysis generated by LLM
CREATE TABLE ai_activity_notes (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    activity_id     UUID NOT NULL REFERENCES activities(id) ON DELETE CASCADE,
    summary         TEXT NOT NULL,
    detail          TEXT,
    model_id        VARCHAR(100) NOT NULL,
    provider_name   VARCHAR(50) NOT NULL,
    generated_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),

    CONSTRAINT uq_ai_activity_notes_activity UNIQUE (activity_id)
);

CREATE INDEX idx_ai_activity_notes_activity ON ai_activity_notes(activity_id);

-- Background job queue for generating AI notes without overloading the backend
CREATE TABLE ai_note_queue (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    activity_id     UUID NOT NULL REFERENCES activities(id) ON DELETE CASCADE,
    status          VARCHAR(20) NOT NULL DEFAULT 'pending',
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    started_at      TIMESTAMP WITH TIME ZONE,
    completed_at    TIMESTAMP WITH TIME ZONE,
    error_message   TEXT,
    retry_count     INT NOT NULL DEFAULT 0,

    CONSTRAINT chk_note_queue_status CHECK (status IN ('pending', 'processing', 'completed', 'failed'))
);

CREATE INDEX idx_ai_note_queue_status ON ai_note_queue(status);
CREATE INDEX idx_ai_note_queue_activity ON ai_note_queue(activity_id);
