ALTER TABLE ai_settings
    ADD COLUMN coaching_style VARCHAR(32) NOT NULL DEFAULT 'BALANCED_ADVISOR'
        CHECK (coaching_style IN ('BALANCED_ADVISOR', 'CONSERVATIVE_SCIENTIST', 'AGGRESSIVE_COACH'));
